/**
 * The API-credential flow, browser to script, against the running demo.
 *
 * A person enrolls a real passkey through a CDP virtual authenticator, mints an
 * API credential in the page — where the key pair is generated by the page's own
 * software authenticator and the private half never reaches the server — and then
 * the actual CLI script authenticates with the resulting `.env` over HTTP.
 *
 * Which makes this the end-to-end claim of the whole design: no browser, no human
 * and no biometric are involved past the first step, and the server verifies
 * every assertion with the same code path a platform authenticator uses.
 */

import type { BrowserContext, Page } from '@playwright/test';

import { expect, test } from '@playwright/test';
import { execFile } from 'node:child_process';
import { mkdirSync, mkdtempSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { promisify } from 'node:util';

import { createUserHandle } from '@localwebauthn/server';
import { randomUUID } from 'node:crypto';

import { createDemoApplication } from '../src/application';
import { openDemoDatabase } from '../src/database';

const run = promisify(execFile);
const repositoryRoot = resolve(import.meta.dirname, '../../..');

async function addVirtualPasskey(context: BrowserContext, page: Page) {
  const client = await context.newCDPSession(page);
  await client.send('WebAuthn.enable');
  await client.send('WebAuthn.addVirtualAuthenticator', {
    options: {
      protocol: 'ctap2',
      transport: 'internal',
      hasResidentKey: true,
      hasUserVerification: true,
      isUserVerified: true,
      automaticPresenceSimulation: true,
    },
  });
}

/** Screenshot for the README, only when a capture directory is set. */
async function capture(page: Page, name: string): Promise<void> {
  const screenshotDirectory = process.env.DEMO_SCREENSHOT_DIR;
  if (!screenshotDirectory) {
    return;
  }
  const directory = resolve(screenshotDirectory);
  mkdirSync(directory, { recursive: true });
  await page.screenshot({ path: resolve(directory, name), fullPage: true });
}

/**
 * An enrollment URL for a person created just for this test.
 *
 * Deliberately not the bootstrap administrator: `lifecycle.spec.ts` expects to be
 * the one that enrolls it, and specs run in filename order, so consuming it here
 * would break that one. Each call makes its own user, so these tests disturb
 * nothing and do not care what ran before.
 */
async function enrollmentUrl(): Promise<{ url: string; email: string }> {
  const database = openDemoDatabase('examples/demo/.data/e2e.db');
  const { authentication } = createDemoApplication(database, {
    auth: {
      publicOrigin: 'http://localhost:4173',
      rpId: 'localhost',
      rpName: 'LocalWebAuthn Demo',
    },
  });
  const id = randomUUID();
  const email = `api-key-${id}@example.test`;
  database
    .prepare(
      `INSERT INTO demo_clients(
         id, email, display_name, role, webauthn_user_handle, created_at
       ) VALUES (?, ?, 'API Key Tester', 'administrator', ?, ?)`,
    )
    .run(id, email, createUserHandle(), Date.now());
  const enrollment = await authentication.issueEnrollment(id);
  database.close();
  return { url: enrollment.enrollmentUrl, email };
}

test('a person mints an API credential, and the CLI script uses it', async ({ page }) => {
  await addVirtualPasskey(page.context(), page);
  const person = await enrollmentUrl();
  const document = await page.goto(person.url);

  // The page about to hold a private key must arrive hardened. Asserted on the
  // real response rather than on the helper, because the value of a header is
  // whether it reaches the browser.
  const csp = document?.headers()['content-security-policy'] ?? '';
  expect(csp).toContain("default-src 'self'");
  expect(csp).not.toContain('unsafe-inline');
  expect(csp).toContain("frame-ancestors 'none'");
  expect(document?.headers()['cache-control']).toContain('no-store');

  await page.getByRole('button', { name: 'Create passkey' }).click();
  await expect(page.getByRole('heading', { name: 'Manage access' })).toBeVisible();

  // The label arrives through a window.prompt, so answer it before clicking.
  page.once('dialog', (dialog) => {
    void dialog.accept('nightly export');
  });
  await page.getByRole('button', { name: 'Create API credential' }).click();

  // Displayed once, because the server holds only the public half and could not
  // reissue this even if asked.
  const env = page.locator('#api-key-env');
  await expect(env).toBeVisible();
  const contents = (await env.textContent()) ?? '';
  expect(contents).toContain('LWA_CREDENTIAL=');
  expect(contents).toContain('LWA_CREDENTIAL_KEY=');
  // Two data lines plus the label comment.
  expect(contents.split('\n').filter((line) => line.trim() && !line.startsWith('#'))).toHaveLength(
    2,
  );

  // It is listed as an API credential, separately from the person's passkey.
  await expect(page.getByRole('heading', { name: 'API credentials' })).toBeVisible();
  await expect(page.getByText('service · Last used')).toBeVisible();

  // Capture for the README only after dismissing the one-time panel: that panel
  // holds a real private key, and a committed screenshot must not.
  await page.getByRole('button', { name: 'Done' }).click();
  await expect(env).toBeHidden();
  await capture(page, 'demo-api-credential.png');

  // Hand the file to the real CLI, pointed at the running demo server.
  const directory = mkdtempSync(join(tmpdir(), 'lwa-e2e-'));
  const envPath = join(directory, 'nightly.env');
  writeFileSync(envPath, contents, { mode: 0o600 });

  const { stdout } = await run('node', ['--import', 'tsx', 'scripts/api-client.ts', envPath], {
    cwd: join(repositoryRoot, 'examples/demo'),
  });
  expect(stdout).toContain('session opened');
  expect(stdout).toContain('"credentialKind": "service"');
  expect(stdout).toContain(person.email);

  // --dry-run prints the bytes: 37-byte authData, flags 0x05 (UP|UV), counter 0.
  const dry = await run(
    'node',
    ['--import', 'tsx', 'scripts/api-client.ts', envPath, '--dry-run'],
    { cwd: join(repositoryRoot, 'examples/demo') },
  );
  expect(dry.stdout).toContain('37 bytes, flags 0x05');
  expect(dry.stdout).toContain('signCount 0');
  expect(dry.stdout).toContain('"typ":"dpop+jwt"');

  // The private key never left the page: the file the browser produced is the
  // only copy, and the server stores a public key.
  expect(readFileSync(envPath, 'utf8')).toBe(contents);
});

test('revoking the API credential stops the script', async ({ page }) => {
  await addVirtualPasskey(page.context(), page);
  await page.goto((await enrollmentUrl()).url);
  await page.getByRole('button', { name: 'Create passkey' }).click();
  await expect(page.getByRole('heading', { name: 'Manage access' })).toBeVisible();

  page.once('dialog', (dialog) => {
    void dialog.accept('doomed export');
  });
  await page.getByRole('button', { name: 'Create API credential' }).click();
  const contents = (await page.locator('#api-key-env').textContent()) ?? '';

  const directory = mkdtempSync(join(tmpdir(), 'lwa-e2e-'));
  const envPath = join(directory, 'doomed.env');
  writeFileSync(envPath, contents, { mode: 0o600 });
  const cwd = join(repositoryRoot, 'examples/demo');
  await expect(
    run('node', ['--import', 'tsx', 'scripts/api-client.ts', envPath], { cwd }),
  ).resolves.toBeTruthy();

  await page.getByRole('button', { name: /^Revoke doomed export$/u }).click();
  await expect(page.getByText('API credential revoked')).toBeVisible();

  await expect(
    run('node', ['--import', 'tsx', 'scripts/api-client.ts', envPath], { cwd }),
  ).rejects.toThrow(/authentication_failed/u);

  // The person is still signed in; only the machine credential went.
  await expect(page.getByRole('heading', { name: 'Manage access' })).toBeVisible();
});
